---
- hosts: remotehost
  remote_user: user
  vars:
      apr_ver: "1.6.2"
      apr_dir: "/opt/apr"
  tasks:

        - name: Download APR
          unarchive:
                src: http://apache.claz.org/apr/apr-{{apr_ver}}.tar.gz
                dest: /opt/
                remote_src: yes

        - name: Compile APR
          command: ./configure --prefix={{ apr_dir }}/{{ apr_ver }}
          args:
              chdir: '{{ apr_dir }}-{{ apr_ver }}'

        - name: Build APR
          make:
              chdir: '{{ apr_dir }}-{{ apr_ver }}'

        - name: Install APR
          make:
              chdir: '{{ apr_dir }}-{{ apr_ver }}'
              target: install

        - name: Changing Current
          file:
              src: '{{ apr_dir }}/{{ apr_ver }}'
              dest: '{{ apr_dir }}/current'
              owner: root
              group: root
              state: link

        - name: Change Ownership
          file:
              path: '{{ apr_dir }}'
              owner: root
              group: root
              recurse: yes

        - name: Remove download and build directory
          file:
              path: '{{ item }}'
              state: absent
          with_items:
              - '{{ apr_dir }}-{{ apr_ver }}'
